Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Style/SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic
