Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Style/SignalException:
  EnforcedStyle: only_raise
  SupportedStyles:
    - only_raise
    - only_fail
    - semantic

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200
